Create table EMP(EMPNO number(4) primary key,Ename varchar(10),JOB Varchar(9), MGR number(4),Hiredate date,SAL number(7,2),Comm Number(7,2),Deptno number(2));

insert into EMP values(7369,'SMITH','CLERK',7902,'17-Dec-80',800,null,20);

SELECT COUNT(*) FROM EMP;

SELECT MIN(SAL),MAX(SAL),AVG(SAL),SUM(SAL) FROM EMP;

SELECT MAX(SAL) FROM EMP WHERE JOB='CLERK';

SELECT SUM(SAL) FROM EMP WHERE DEPTNO=20 AND JOB='ANALYST';

SELECT DEPTNO,COUNT(*) FROM EMP GROUP BY DEPTNO;

SELECT JOB,COUNT(*) FROM EMP GROUP BY JOB;

SELECT JOB,MIN(SAL), FROM EMP GROUP BY JOB;

SELECT JOB,MIN(SAL),MAX(SAL),AVG(SAL),SUM(SAL) FROM EMP GROUP BY JOB;

SELECT DEPTNO,JOB,COUNT(*) FROM EMP GROUP BY DEPTNO,JOB;

SELECT DEPTNO,JOB,COUNT(*) FROM EMP WHERE DEPTNO=20 GROUP BY DEPTNO,JOB;

SELECT DEPTNO,JOB,COUNT(*) FROM EMP WHERE DEPTNO=20 GROUP BY DEPTNO,JOB HAVING COUNT(*)>1 ORDER BY JOB;
