CREATE TABLE BUS (ROUTENO NUMBER(4) PRIMARY KEY, SOURCE VARCHAR(15),DESTINATION VARCHAR(15));

CREATE TABLE PASSENGER (PID NUMBER(4) PRIMARY KEY,PNAME VARCHAR(15),DOB DATE,GENDER VARCHAR(6));

CREATE TABLE BOOK_TICKET(PID NUMBER(4) REFERENCES PASSENGER(PID),ROUTENO NUMBER(4) REFERENCES BUS(ROUTENO), JOURNEY_DATE DATE,SEAT_NO VARCHAR(5), PRIMARY KEY(PID,ROUTENO,JOURNEY_DATE));

insert into bus values(&ROUTENO,'&SOURCE','&DESTINATION');

insert into PASSENGER VALUES(&PID,'&PNAME','&DOB','&GENDER');

insert into BOOK_TICKET VALUES(&PID,&ROUTENO,'&JOURNEY_DATE','&SEATNO');

COMMIT;

SELECT * FROM BUS;

SELECT * FROM PASSENGER;

SELECT * FROM BOOK_TICKET;

SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME='BUS';

SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME='PASSENGER';

SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,R_CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='BOOK_TICKET';
